version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: just-real-estate-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: just_real_estate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: chadeeboo/backend:latest
    container_name: just-real-estate-backend
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: just_real_estate
      PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    image: chadeeboo/frontend:latest
    container_name: just-real-estate-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
